# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67e5ed451f20d11be2d39e1b79c075d511980c86fdecba47f06ed5d712cad1717128e8de9b44e88499857c35465d6e5cd1187490a9f88ab2340eb2fe80d948bb

test:
  secret_key_base: b9c740b8dcaa6d136a0e18842fd07355373d057ebdf72c89db139a4897d0ab2a5ad6b3fb7744fad5ccd3b674c7068035769b34cb5a6fac7b30cc57513a3d73dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
